version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.5
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.2
    - 1.15.3
  - dependency-name: com.github.spotbugs:spotbugs
    versions:
    - 4.2.3
  - dependency-name: org.testcontainers:nginx
    versions:
    - 1.15.2
    - 1.15.3
  - dependency-name: org.testcontainers:selenium
    versions:
    - 1.15.2
    - 1.15.3
