language: java
jobs:
  include:
    - stage: check
      name: test
      script: mvn test
    - name: validate
      script: mvn validate
    - stage: build image
      install: true
      script: docker build .
      if: type = pull_request
    - stage: push image
      install: true
      script:
        - docker build -t alexpdp7/zqxjkcrud:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push alexpdp7/zqxjkcrud:latest
      if: type = push AND branch = master
branches:
  only: 
    - master
