on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo check
      working-directory: manifest-builder
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy
      working-directory: manifest-builder
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt --check
      working-directory: manifest-builder
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo test
      working-directory: manifest-builder
